sudo: false

before_install:
  - gem install bundler
  - gem update bundler
matrix:
  include:
     - rvm: 1.9.3
     - rvm: 2.0.0
     - rvm: 2.1.10
     - rvm: 2.2.5
     - rvm: 2.3.1
     - rvm: jruby-1.7.26
       env: JRUBY_OPTS='--dev'
     - rvm: jruby-9.1.2.0
       env: JRUBY_OPTS='--dev'
gemfile:
  - gemfiles/i18n_0.4.gemfile
  - gemfiles/i18n_0.5.gemfile
  - gemfiles/i18n_0.6.gemfile
  - gemfiles/i18n_0.7.gemfile
notifications:
  slack:
    secure: JryUWfe2JR0cfNT+TIHwryy8NS8m9/hbRhg+5UqwuYWuEp6gtcWCA05wKsajQyRrGaNGYKu81RA9jpQrirgQWzDUJl5o3sEWbqKZv3pW0ybn8Tx52N1mxW3Puar5KLZ8TPRphKKIJ8/1EhAh4zpC5Mtxv8Sz1/AHuqnlu6l+bb4=
